services:
  postgres:
    image: postgres:18-alpine
    container_name: estoque_postgres
    environment:
      POSTGRES_USER: joaogstex
      POSTGRES_PASSWORD: euAmoAndressaEStarWars
      POSTGRES_DB: estoque_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: